server:
  port: 9020

spring:
  application:
    name: food-availability-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    ServiceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost