server:
    port: 9011

spring:
  application:
    name: ticket-history-service

eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
      ServiceUrl:
        defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost