server:
  port: 9003

spring:
  application:
    name: movie-reserve-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    ServiceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost