server:
  port: 9002

spring:
  application:
    name: movie-check-availability-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    ServiceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost