server:
    port: 9010

spring:
  application:
    name: take-ticket-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    ServiceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
