server:
  port: 9015

spring:
  application:
    name: movies-advertised-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    ServiceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost