server:
    port: 9006

spring:
    application:
        name: payment-calculator-service

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        ServiceUrl:
            defaultZone: http://localhost:8761/eureka
    instance:
        hostname: localhost