server:
    port: 9008

spring:
    application:
        name: billing-history-service

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        ServiceUrl:
            defaultZone: http://localhost:8761/eureka
    instance:
        hostname: localhost